backend:
  name: github
  repo: nhsconnect/gpconnect
  branch: develop

media_folder: "images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "accessrecord"
    label: "Access Record HTML"
    folder: "_pages/accessrecord"
    create: false
    slug: "accessrecord_{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Page Title For Browser"}
      - {label: "Key Words", name: "keywords", widget: "hidden", default: "getcarerecord"}
      - {label: "Tags", name: "thumbnail", widget: "hidden", default: "getcarerecord"}
      - {label: "Sidebar", name: "sidebar", widget: "hidden", default: "accessrecord_sidebar"}
      - {label: "Permalink", name: "permalink", widget: "string", default: "accessrecord_{{slug}}.html"}
      - {label: "Summary", name: "summary", widget: "string", default: "Summary of page content."}
      - {label: "Body", name: "body", widget: "markdown"}
